import UI from "../UI.js";

document.addEventListener("DOMContentLoaded", () => {
    let ui = new UI({ title: 'Test UI', theme: 'light noback' })
        .addFile('file', 'File')
        .addText('text', 'Text', '')
        .addNumber('number', 'Number', 128, 1)
        .addRange('range', 'Range', 0, -180, 180, 5)
        .addSelect('select', 'Select', ['Mode 1', 'mode2', 'MODE_3'])
        .addHTML('html', 'HTML', '<h2>Hello</h2>')
        .addSwitch('switch', 'Switch', 0)
        .addColor('color', 'Color')
        .addSpace()
        .addArea('area', 'Area', 'abc')
        .addButtons({ 'btn1': ['Button 1', null], 'btn2': 'Button 2' })
        .addButton('button', 'Button')

    ui.onChange((id, val, t) => console.log(id, val, t));

    new UI({ x:'210px',title: 'Test UI', theme: 'dark noback' })
        .addFile('file', 'File')
        .addText('text', 'Text', '')
        .addNumber('number', 'Number', 128, 1)
        .addRange('range', 'Range', 0, -180, 180, 5)
        .addSelect('select', 'Select', ['Mode 1', 'mode2', 'MODE_3'])
        .addHTML('html', 'HTML', '<h2>Hello</h2>')
        .addSwitch('switch', 'Switch', 0)
        .addColor('color', 'Color')
        .addSpace()
        .addArea('area', 'Area', 'abc')
        .addButtons({ 'btn1': ['Button 1', null], 'btn2': 'Button 2' })
        .addButton('button', 'Button')
            new UI({ x:'420px',title: 'Test UI', theme: 'light ' })
        .addFile('file', 'File')
        .addText('text', 'Text', '')
        .addNumber('number', 'Number', 128, 1)
        .addRange('range', 'Range', 0, -180, 180, 5)
        .addSelect('select', 'Select', ['Mode 1', 'mode2', 'MODE_3'])
        .addHTML('html', 'HTML', '<h2>Hello</h2>')
        .addSwitch('switch', 'Switch', 0)
        .addColor('color', 'Color')
        .addSpace()
        .addArea('area', 'Area', 'abc')
        .addButtons({ 'btn1': ['Button 1', null], 'btn2': 'Button 2' })
        .addButton('button', 'Button')
            new UI({ x:'630px',title: 'Test UI', theme: 'dark' })
        .addFile('file', 'File')
        .addText('text', 'Text', '')
        .addNumber('number', 'Number', 128, 1)
        .addRange('range', 'Range', 0, -180, 180, 5)
        .addSelect('select', 'Select', ['Mode 1', 'mode2', 'MODE_3'])
        .addHTML('html', 'HTML', '<h2>Hello</h2>')
        .addSwitch('switch', 'Switch', 0)
        .addColor('color', 'Color')
        .addSpace()
        .addArea('area', 'Area', 'abc')
        .addButtons({ 'btn1': ['Button 1', null], 'btn2': 'Button 2' })
        .addButton('button', 'Button')

    // ui.removeAll();
});